version: "3"

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - 443:443
      - 80:80
    restart: always
    volumes:
      - ./requirements/volume:/var/www/html
    depends_on:
      - wordpress
    networks:
      - suhkim_network

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    restart: always
    volumes:
      - ./requirements/volume:/var/www/html
    expose:
      - "9000"
    networks:
      - suhkim_network

networks:
  suhkim_network:
    driver: bridge

volumes:
  nginx:
  wordpress:
